import { useState } from 'react';
import { motion } from 'motion/react';
import {
  Files,
  FileText,
  Download,
  Sparkles,
  ChevronRight,
  ShieldCheck,
  Languages,
  CheckCircle2,
} from 'lucide-react';
import { Button } from '@/components/ui/button';
import { SpotlightCard } from '@/src/components/SpotlightCard';
import { jsPDF } from 'jspdf';

// ── Sample Case Profile ──────────────────────────────────────────────────────
const C = {
  accusedName: 'Ramesh Kumar Sharma',
  accusedAge: '34',
  accusedFather: 'Late Suresh Kumar Sharma',
  accusedAddress: '#42, 5th Cross, Koramangala 4th Block, Bengaluru - 560034',
  accusedOccupation: 'Carpenter',
  firNo: '0442/2026',
  crimeDate: '30.04.2026',
  arrestDate: '02.05.2026',
  policeStation: 'Koramangala Police Station, South Division, Bengaluru',
  sections: 'Sections 303(2) and 333(1) of BNS, 2023',
  courtName: 'Additional Sessions Judge, Bengaluru Urban District',
  courtRoom: 'Court Room No. 3, ASJ Court Complex, Bengaluru',
  judgeFullName: 'Hon\'ble Shri Justice P.K. Reddy',
  caseNo: 'Crl.Misc.No.            /2026',
  complainant: 'Mukesh Agarwal',
  complainantAddress: 'Agarwal Electronics, 80 Feet Road, Koramangala, Bengaluru',
  advocate: 'Adv. S. Murthy',
  advocateEnrol: 'KAR/2009/1234',
  advocatePhone: '+91-98450-12345',
  today: new Date().toLocaleDateString('en-IN', { day: '2-digit', month: 'long', year: 'numeric' }),
};

// ── PDF Builder helper ───────────────────────────────────────────────────────
function makePDF() {
  const doc = new jsPDF({ orientation: 'p', unit: 'mm', format: 'a4' });
  const M = 22;   // left margin
  const W = 166;  // content width
  let y = 22;

  const newPage = () => { doc.addPage(); y = 22; };
  const check = () => { if (y > 268) newPage(); };

  const center = (text: string, size = 11, bold = true) => {
    doc.setFontSize(size); doc.setFont('helvetica', bold ? 'bold' : 'normal');
    doc.splitTextToSize(text, W).forEach((line: string) => {
      doc.text(line, M + W / 2, y, { align: 'center' }); y += size * 0.42 + 1;
    });
  };

  const left = (text: string, size = 10, bold = false, indent = 0) => {
    doc.setFontSize(size); doc.setFont('helvetica', bold ? 'bold' : 'normal');
    const lines = doc.splitTextToSize(text, W - indent);
    doc.text(lines, M + indent, y);
    y += lines.length * (size * 0.42 + 1) + 1;
  };

  const right = (text: string, size = 10) => {
    doc.setFontSize(size); doc.setFont('helvetica', 'normal');
    doc.text(text, M + W, y, { align: 'right' });
  };

  const hr = (gap = 4) => {
    doc.setDrawColor(90); doc.line(M, y, M + W, y); y += gap;
  };

  const sp = (mm = 5) => { y += mm; };

  const footer = () => {
    doc.setFontSize(7); doc.setTextColor(130);
    doc.text(
      'DRAFT — GENERATED BY BAILBRIDGE AI / NAMMA NYAYA AGENT — NOT FOR SUBMISSION WITHOUT ADVOCATE REVIEW',
      M + W / 2, 286, { align: 'center' }
    );
    doc.setTextColor(0);
  };

  return { doc, center, left, right, hr, sp, check, newPage, footer, M, W, get y() { return y; }, set y(v) { y = v; } };
}

// ── Template 1: Bail Application ─────────────────────────────────────────────
function generateBailApplication(lang: string) {
  const b = makePDF();

  b.center('IN THE COURT OF THE ADDITIONAL SESSIONS JUDGE');
  b.center('BENGALURU URBAN DISTRICT, BENGALURU');
  b.sp(2);
  b.center(C.caseNo, 10, false);
  b.sp(3); b.hr();

  b.left('State of Karnataka');
  b.right('... Respondent/State');
  b.sp(3);
  b.center('— VERSUS —', 10, true);
  b.sp(3);
  b.left(C.accusedName);
  b.right('... Petitioner/Accused');
  b.left(`S/o ${C.accusedFather}, Age: ${C.accusedAge} Yrs, Occ: ${C.accusedOccupation}`, 9, false, 5);
  b.left(`R/at: ${C.accusedAddress}`, 9, false, 5);
  b.sp(3); b.hr();

  b.sp(3);
  if (lang === 'kn') b.center('ನಿಯಮಿತ ಜಾಮೀನಿಗಾಗಿ ಅರ್ಜಿ (BNSS ಸೆಕ್ 480)', 10, true);
  b.center('APPLICATION FOR REGULAR BAIL UNDER SECTION 480 OF THE', 10);
  b.center('BHARATIYA NAGARIK SURAKSHA SANHITA (BNSS), 2023', 10);
  b.sp(3); b.hr(); b.sp(5);

  b.left('The Petitioner above named most respectfully submits as under:');
  b.sp(5);

  [
    `The Petitioner is arrayed as Accused No.1 in Crime No. ${C.firNo} registered at ${C.policeStation} under ${C.sections}. The Petitioner was arrested on ${C.arrestDate} and is presently in judicial custody at the Central Prison, Bengaluru.`,
    'The Petitioner is a first-time offender with absolutely no prior criminal antecedents, pending cases, or adverse entries in any police record in India.',
    `The Petitioner is the sole breadwinner of his family comprising his wife Smt. Kavitha R. Sharma and two minor children aged 7 and 4 years. His continued incarceration has caused severe financial hardship and emotional distress to his dependents.`,
    'The investigation is substantially complete. A portion of the alleged stolen goods has been recovered by the investigating officer. No further custodial interrogation of the Petitioner is necessary.',
    `The Petitioner respectfully undertakes to abide by all conditions this Hon'ble Court deems fit, including: (a) reporting to ${C.policeStation} every Saturday between 10:00 AM and 12:00 Noon; (b) not leaving the jurisdiction of Bengaluru without prior written leave of Court; (c) not tampering with evidence, influencing witnesses, or approaching the complainant; and (d) surrendering his travel documents.`,
    "The continued detention of the Petitioner is violative of the fundamental right to personal liberty guaranteed under Article 21 of the Constitution of India and the presumption of innocence, a foundational principle of criminal jurisprudence.",
  ].forEach((g, i) => {
    b.check();
    b.left(`${i + 1}.   ${g}`, 10, false, 5);
    b.sp(4);
  });

  b.check(); b.sp(3);
  b.left('PRAYER', 11, true); b.sp(4);
  b.left("In view of the foregoing submissions, it is most respectfully prayed that this Hon'ble Court may be pleased to:");
  b.sp(4);
  b.left(`(a)   Grant regular bail to the Petitioner in Crime No. ${C.firNo} registered at ${C.policeStation} on such terms and conditions as this Hon'ble Court may deem just and proper;`, 10, false, 10);
  b.sp(4);
  b.left("(b)   Pass such other orders as this Hon'ble Court deems fit in the interests of justice and equity.", 10, false, 10);
  b.sp(12);

  b.left(`Place: Bengaluru`); b.left(`Date:  ${C.today}`); b.sp(18);

  b.doc.setFontSize(10); b.doc.setFont('helvetica', 'normal');
  [`(${C.advocate})`, 'Advocate for the Petitioner', `Enrollment No: ${C.advocateEnrol}`, `Mobile: ${C.advocatePhone}`].forEach(line => {
    b.doc.text(line, b.M + b.W, b.y, { align: 'right' }); b.y += 6;
  });

  b.hr(3); b.footer();
  b.doc.save(`BailBridge_BailApplication_${C.accusedName.replace(/ /g, '_')}.pdf`);
}

// ── Template 2: FIR Copy Request ─────────────────────────────────────────────
function generateFIRRequest(lang: string) {
  const b = makePDF();

  b.center('APPLICATION FOR CERTIFIED COPY OF FIRST INFORMATION REPORT');
  b.center('(Under Section 173(2), BNSS 2023 & Section 50A of the Police Act)', 9, false);
  b.sp(5); b.hr();

  b.sp(5);
  b.left('To,'); b.sp(1);
  b.left('The Station House Officer,', 10, true); b.sp(1);
  b.left(`${C.policeStation},`); b.left('Bengaluru — 560034.');
  b.sp(8);
  b.left('Sub: Request for Certified Copy of FIR No. 0442/2026.', 10, true);
  b.sp(5);
  b.left('Respected Sir/Madam,'); b.sp(4);

  b.left(`I, Kavitha R. Sharma, W/o ${C.accusedName}, residing at ${C.accusedAddress}, do hereby most respectfully state as follows:`); b.sp(5);

  [
    `My husband, ${C.accusedName}, has been arrested and detained in connection with FIR No. ${C.firNo} registered at your police station on ${C.crimeDate} under ${C.sections}.`,
    `As the wife of the accused and a directly affected person, I am legally entitled to obtain a certified copy of the said FIR under Section 173(2) of the Bharatiya Nagarik Suraksha Sanhita (BNSS), 2023, as well as under the Right to Information Act, 2005.`,
    'My family requires the certified copy to consult an advocate, apply for bail before the competent court, and exercise the constitutional rights of the accused.',
    'I am prepared to pay all applicable fees and furnish proof of identity and relationship upon request.',
  ].forEach((p, i) => {
    b.check();
    b.left(`${i + 1}.   ${p}`, 10, false, 5);
    b.sp(4);
  });

  b.sp(3);
  b.left('PRAYER:', 10, true); b.sp(3);
  b.left(`It is therefore respectfully prayed that your good office may be pleased to provide a certified copy of FIR No. ${C.firNo} at the earliest, to enable the family to take steps for the legal representation and bail of ${C.accusedName}.`);
  b.sp(12);
  b.left(`Place: Bengaluru`); b.left(`Date:  ${C.today}`); b.sp(15);

  b.doc.setFontSize(10); b.doc.setFont('helvetica', 'normal');
  ['(Kavitha R. Sharma)', 'Wife of the Accused', `Contact: +91-99001-22334`].forEach(line => {
    b.doc.text(line, b.M + b.W, b.y, { align: 'right' }); b.y += 6;
  });

  b.hr(3); b.footer();
  b.doc.save('BailBridge_FIR_Copy_Request_0442_2026.pdf');
}

// ── Template 3: DLSA Legal Aid Application ────────────────────────────────────
function generateDLSAApplication(lang: string) {
  const b = makePDF();

  b.center('DISTRICT LEGAL SERVICES AUTHORITY');
  b.center('BENGALURU URBAN DISTRICT, BENGALURU');
  b.sp(3); b.hr();
  b.sp(3);
  b.center('APPLICATION FOR FREE LEGAL AID UNDER SECTION 12 OF THE', 10);
  b.center('LEGAL SERVICES AUTHORITIES ACT, 1987', 10);
  b.sp(4); b.hr(); b.sp(5);

  b.left('To,'); b.sp(1);
  b.left('The Secretary,', 10, true); b.left('District Legal Services Authority (DLSA),'); b.left('City Civil Court Complex, Bengaluru — 560001.');
  b.sp(7);
  b.left('Sub: Application for Free Legal Aid for undertrial prisoner.', 10, true);
  b.sp(5); b.left('Respected Sir/Madam,'); b.sp(5);

  b.left(`I, Kavitha R. Sharma, W/o Sri ${C.accusedName}, S/o ${C.accusedFather}, aged ${C.accusedAge} years, residing at ${C.accusedAddress}, hereby apply for free legal aid on behalf of my husband who is currently an undertrial prisoner in connection with Crime No. ${C.firNo} of ${C.policeStation}.`);
  b.sp(5);

  b.left('DETAILS OF THE ACCUSED UNDERTRIAL PRISONER:', 10, true); b.sp(3);

  const rows: [string, string][] = [
    ['Full Name', C.accusedName],
    ['Father\'s Name', C.accusedFather],
    ['Age / D.O.B.', '34 Years / 15.03.1992'],
    ['Occupation', C.accusedOccupation],
    ['Address', C.accusedAddress],
    ['FIR No. & Date', `${C.firNo}, dated ${C.crimeDate}`],
    ['Police Station', C.policeStation],
    ['Sections Invoked', C.sections],
    ['Date of Arrest', C.arrestDate],
    ['Place of Custody', 'Central Prison, Parappana Agrahara, Bengaluru — 560100'],
    ['Court', `${C.courtName}, ${C.caseNo}`],
  ];

  rows.forEach(([label, val]) => {
    b.check();
    b.doc.setFontSize(9); b.doc.setFont('helvetica', 'bold');
    b.doc.text(label + ':', b.M + 5, b.y);
    b.doc.setFont('helvetica', 'normal');
    const lines = b.doc.splitTextToSize(val, 100);
    b.doc.text(lines, b.M + 65, b.y);
    b.y += Math.max(lines.length, 1) * 5 + 2;
  });

  b.sp(4); b.hr(); b.sp(4);
  b.left('DECLARATION:', 10, true); b.sp(3);
  b.left('I hereby solemnly declare that my family\'s annual income is below Rs. 3,00,000 (Three Lakhs) and we are unable to engage an advocate for the defence of the accused due to financial constraints. I undertake to produce supporting income certificates if required.', 10, false, 5);
  b.sp(8);
  b.left(`Place: Bengaluru`); b.left(`Date:  ${C.today}`); b.sp(14);

  b.doc.setFontSize(10); b.doc.setFont('helvetica', 'normal');
  ['(Kavitha R. Sharma)', 'Applicant — Wife of Accused', 'Contact: +91-99001-22334'].forEach(line => {
    b.doc.text(line, b.M + b.W, b.y, { align: 'right' }); b.y += 6;
  });

  b.hr(3); b.footer();
  b.doc.save('BailBridge_DLSA_LegalAid_Application.pdf');
}

// ── Template 4: Memo of Protest ───────────────────────────────────────────────
function generateMemoOfProtest(lang: string) {
  const b = makePDF();

  b.center('MEMORANDUM OF PROTEST');
  b.center('(Under Section 175, BNSS 2023 — Protest Petition against Police Report)', 9, false);
  b.sp(5); b.hr();

  b.sp(5);
  b.left('To,'); b.sp(1);
  b.left('The Additional Sessions Judge,', 10, true);
  b.left(`${C.courtName},`); b.left(`${C.courtRoom}.`);
  b.sp(6);
  b.left(`Sub: Protest against Investigation and Final Report in Crime No. ${C.firNo} of ${C.policeStation}.`, 10, true);
  b.sp(5);
  b.left(`Ref: ${C.caseNo}`); b.sp(5);

  b.left(`The Petitioner, ${C.accusedName}, represented by the undersigned advocate, hereby files this Memorandum of Protest against the investigation conducted in the above-referenced crime and submits as under:`); b.sp(5);

  [
    `The accused was arrested on ${C.arrestDate} under ${C.sections} in connection with an alleged incident on ${C.crimeDate}. The arrest was made in gross violation of the mandatory guidelines laid down by the Hon'ble Supreme Court in D.K. Basu v. State of West Bengal (1997) 1 SCC 416, and now codified under Section 36 of the BNSS, 2023.`,
    'Specifically, the following procedural violations occurred during the arrest: (a) the accused was not informed of the grounds of arrest in writing; (b) the memo of arrest was not signed by a family member or respectable witness; (c) the arrested person was not informed of his right to legal representation at the time of arrest.',
    'The investigating officer failed to record the exact time of arrest and did not produce the accused before the jurisdictional magistrate within the mandatory 24-hour window stipulated under Section 58 of BNSS, 2023, and Article 22(2) of the Constitution of India.',
    'The alleged recovery of stolen goods was not conducted in the presence of the accused or his counsel, and no panchanama was drawn up in compliance with Section 100, Code of Criminal Procedure (now Section 105, BNSS 2023), raising serious questions about the evidentiary value of the recovery.',
    'The accused denies all allegations and submits that the FIR is based on false and fabricated information provided by the complainant out of personal animosity, and that no credible evidence exists to connect the accused to the alleged offence.',
  ].forEach((g, i) => {
    b.check();
    b.left(`${i + 1}.   ${g}`, 10, false, 5);
    b.sp(5);
  });

  b.check(); b.sp(3);
  b.left('PRAYER:', 10, true); b.sp(3);
  b.left("It is therefore most respectfully prayed that this Hon'ble Court may be pleased to:"); b.sp(4);
  b.left("(a)   Take cognizance of this Memorandum of Protest and direct a fresh, independent, and impartial investigation by a senior officer;", 10, false, 10); b.sp(3);
  b.left("(b)   Direct the competent authority to initiate a departmental inquiry against the investigating officer for procedural violations during arrest;", 10, false, 10); b.sp(3);
  b.left("(c)   Pass such other orders as this Court deems fit and just in the interest of justice.", 10, false, 10);
  b.sp(12);

  b.left(`Place: Bengaluru`); b.left(`Date:  ${C.today}`); b.sp(18);

  b.doc.setFontSize(10); b.doc.setFont('helvetica', 'normal');
  [`(${C.advocate})`, 'Advocate for the Accused/Petitioner', `Enrollment No: ${C.advocateEnrol}`, `Mobile: ${C.advocatePhone}`].forEach(line => {
    b.doc.text(line, b.M + b.W, b.y, { align: 'right' }); b.y += 6;
  });

  b.hr(3); b.footer();
  b.doc.save('BailBridge_MemoOfProtest_Sharma_2026.pdf');
}

// ── Component ─────────────────────────────────────────────────────────────────
const TEMPLATES = [
  {
    id: 'bail-app',
    title: 'Bail Application (BNSS Sec 480)',
    description: 'Regular bail petition for Sessions Court. Pre-filled with FIR No. 0442/2026 — State vs. Ramesh Kumar Sharma.',
    type: 'Legal Petition',
    generate: generateBailApplication,
  },
  {
    id: 'fir-copy',
    title: 'FIR Copy Request',
    description: 'Formal application to the Station House Officer for a certified copy of FIR No. 0442/2026.',
    type: 'Mandatory',
    generate: generateFIRRequest,
  },
  {
    id: 'legal-aid',
    title: 'DLSA Legal Aid Application',
    description: 'Application to the District Legal Services Authority for free state-sponsored legal representation.',
    type: 'Rights',
    generate: generateDLSAApplication,
  },
  {
    id: 'protest',
    title: 'Memo of Protest (D.K. Basu)',
    description: 'Protest petition citing violation of D.K. Basu guidelines and BNSS procedural safeguards during arrest.',
    type: 'Procedural',
    generate: generateMemoOfProtest,
  },
];

const ARCHIVE = [
  { label: 'BailApplication_Draft_v1_07May.pdf', id: 'bail-app' },
  { label: 'DLSA_LegalAid_Application_09May.pdf', id: 'legal-aid' },
];

export default function DocumentArchitect() {
  const [generating, setGenerating] = useState<string | null>(null);
  const [language, setLanguage] = useState<'en' | 'kn'>('en');

  const handleGenerate = (id: string, generate: (lang: string) => void) => {
    setGenerating(id);
    setTimeout(() => { generate(language); setGenerating(null); }, 900);
  };

  return (
    <div className="max-w-6xl mx-auto px-4 py-8">
      <div className="flex items-center gap-8 mb-16 flex-col md:flex-row text-center md:text-left border-b border-white/5 pb-12">
        <div className="w-16 h-16 rounded-xl bg-blue-600/10 flex items-center justify-center text-blue-400 border border-blue-500/20 shrink-0">
          <Files className="w-8 h-8" />
        </div>
        <div className="flex-1">
          <div className="text-[10px] font-black uppercase tracking-[0.3em] text-blue-400 mb-2">Automated Drafting — Case: FIR No. 0442/2026</div>
          <h1 className="text-4xl font-semibold mb-3 text-white uppercase tracking-tight">Document Architect</h1>
          <p className="text-slate-500 max-w-2xl leading-relaxed text-sm italic">
            Court-ready petitions auto-filled with case data for <span className="text-white font-semibold not-italic">State of Karnataka vs. Ramesh Kumar Sharma</span>. Optimised for BNSS 2023.
          </p>
        </div>
        <button
          onClick={() => setLanguage(l => l === 'en' ? 'kn' : 'en')}
          className={`shrink-0 flex items-center gap-2 px-4 py-2.5 rounded-xl border text-[10px] font-black uppercase tracking-widest transition-all ${
            language === 'kn'
              ? 'border-blue-500/40 bg-blue-600/10 text-blue-400'
              : 'border-white/10 bg-white/5 text-slate-400 hover:text-white hover:border-white/20'
          }`}
          title="Toggle document language"
        >
          <Languages className="w-4 h-4" />
          {language === 'en' ? 'English' : 'ಕನ್ನಡ'}
        </button>
      </div>

      <div className="grid grid-cols-1 lg:grid-cols-4 gap-12">
        {/* Templates */}
        <div className="lg:col-span-3 grid grid-cols-1 md:grid-cols-2 gap-6">
          {TEMPLATES.map((tpl) => (
            <motion.div key={tpl.id} whileHover={{ y: -4 }} className="group">
              <SpotlightCard className="p-8 h-full flex flex-col bg-slate-950/40 border-white/5 hover:border-blue-500/30 transition-all">
                <div className="flex justify-between items-start mb-6">
                  <span className="text-[10px] font-black uppercase tracking-widest text-slate-600 border border-white/10 px-2 py-0.5 rounded">
                    {tpl.type}
                  </span>
                  <div className="w-2 h-2 rounded-full bg-blue-500/20 group-hover:bg-blue-500 transition-colors" />
                </div>
                <h3 className="text-lg font-bold mb-3 text-white tracking-tight uppercase">{tpl.title}</h3>
                <p className="text-[13px] text-slate-500 leading-relaxed mb-8 flex-1">{tpl.description}</p>
                <div className="flex gap-3 pt-6 border-t border-white/5">
                  <Button
                    className="flex-1 bg-blue-600 hover:bg-blue-700 text-white font-bold h-11 rounded-lg text-xs uppercase tracking-widest transition-all shadow-lg shadow-blue-600/10"
                    onClick={() => handleGenerate(tpl.id, tpl.generate)}
                    disabled={generating !== null}
                  >
                    {generating === tpl.id ? (
                      <><Sparkles className="mr-2 w-3.5 h-3.5 animate-spin" />Generating...</>
                    ) : (
                      <>Draft Petition<ChevronRight className="ml-2 w-4 h-4" /></>
                    )}
                  </Button>
                </div>
              </SpotlightCard>
            </motion.div>
          ))}
        </div>

        {/* Right Panel */}
        <div className="space-y-8">
          <SpotlightCard className="p-6 bg-slate-900/40">
            <h3 className="text-[10px] font-black tracking-[0.2em] text-slate-500 uppercase mb-6 flex items-center gap-2">
              <ShieldCheck className="w-4 h-4 text-blue-400" />
              Case Details
            </h3>
            <div className="space-y-3 text-[11px]">
              <DetailRow label="Accused" value={C.accusedName} />
              <DetailRow label="FIR No." value={C.firNo} />
              <DetailRow label="Sections" value="BNS 303(2), 333(1)" />
              <DetailRow label="Arrested" value={C.arrestDate} />
              <DetailRow label="Hearing" value="24 May 2026" />
              <DetailRow label="Advocate" value={C.advocate} />
            </div>
          </SpotlightCard>

          <SpotlightCard className="p-6 bg-slate-900/40">
            <h3 className="text-[10px] font-black tracking-[0.2em] text-slate-500 uppercase mb-6 flex items-center gap-2">
              <ShieldCheck className="w-4 h-4 text-blue-400" />
              Submission Protocol
            </h3>
            <div className="space-y-4">
              <CheckItem text="FIR No. 0442/2026 verified" checked />
              <CheckItem text="Police Station details" checked />
              <CheckItem text="Sections BNS 303(2) & 333(1)" checked />
              <CheckItem text="Surety details provided" />
              <CheckItem text="Accused PAN/Aadhaar" />
            </div>
          </SpotlightCard>

          <div>
            <h4 className="text-[10px] font-black text-slate-600 uppercase tracking-widest mb-4 px-1">Previous Drafts</h4>
            <div className="space-y-2">
              {ARCHIVE.map((a) => (
                <div
                  key={a.id}
                  className="flex items-center justify-between group cursor-pointer hover:bg-white/5 p-3 rounded-lg border border-transparent hover:border-white/5 transition-all"
                  onClick={() => handleGenerate(a.id, TEMPLATES.find(t => t.id === a.id)!.generate)}
                >
                  <div className="flex items-center gap-3">
                    <FileText className="w-4 h-4 text-slate-600 group-hover:text-blue-400" />
                    <span className="text-[10px] text-slate-500 font-medium">{a.label}</span>
                  </div>
                  <Download className="w-3.5 h-3.5 text-slate-700 group-hover:text-white" />
                </div>
              ))}
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}

function DetailRow({ label, value }: { label: string; value: string }) {
  return (
    <div className="flex justify-between gap-2">
      <span className="text-slate-600 font-bold uppercase tracking-wide shrink-0">{label}</span>
      <span className="text-slate-300 font-mono text-right truncate">{value}</span>
    </div>
  );
}

function CheckItem({ text, checked = false }: { text: string; checked?: boolean }) {
  return (
    <div className="flex items-center gap-3 text-xs">
      <div className={`w-4 h-4 rounded-full border ${checked ? 'bg-emerald-500 border-emerald-500' : 'border-white/20'} flex items-center justify-center shrink-0`}>
        {checked && <CheckCircle2 className="w-3 h-3 text-white" />}
      </div>
      <span className={checked ? 'text-slate-300' : 'text-slate-500'}>{text}</span>
    </div>
  );
}
