import { useState } from 'react';
import { motion } from 'motion/react';
import { QRCodeSVG } from 'qrcode.react';
import { 
  Files, 
  FileText, 
  Download, 
  Printer, 
  Sparkles, 
  ChevronRight,
  ShieldCheck,
  Languages,
  CheckCircle2,
  QrCode
} from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Card, CardHeader, CardTitle, CardContent } from '@/components/ui/card';
import { Badge } from '@/components/ui/badge';
import { SpotlightCard } from '@/src/components/SpotlightCard';
import { ScrollArea } from '@/components/ui/scroll-area';
import { jsPDF } from "jspdf";
import "jspdf-autotable";

export default function DocumentArchitect() {
  const [generating, setGenerating] = useState<string | null>(null);
  const [showQR, setShowQR] = useState(false);

  // Check for extracted FIR data
  const storedFIR = localStorage.getItem('bailbridge_extracted_fir');
  const extractedDetails = storedFIR ? JSON.parse(storedFIR) : null;

  const mockCaseData = {
    caseId: extractedDetails?.fir_number || "BB-2024-8842",
    offence: extractedDetails?.sections_charged || "BNS-303 (Petty Theft)",
    rights: "Article 21/39A Protection",
    pincode: extractedDetails?.police_station ? "Verified" : "560001",
    timestamp: new Date().toISOString(),
    station: extractedDetails?.police_station || "N/A"
  };

  const templates = [
    { id: 'legal-aid-form1', title: 'NALSA Form 1 (Legal Aid)', description: 'Official request for state-sponsored free lawyer (Article 39A). Use this if family income is below threshold.', type: 'Rights' },
    { id: 'bail-app', title: 'Bail Application (Sec 437/439)', description: 'Standard petition for interim or regular bail in sessions/magistrate court.', type: 'Legal Petition' },
    { id: 'fir-copy', title: 'FIR Copy Request', description: 'Formal application to obtain certified copy of First Information Report.', type: 'Mandatory' },
    { id: 'autobail-notice', title: 'Sec 479 Notice (1/3rd Rule)', description: 'Notice to Jail Superintendent for automatic release of first-time offenders.', type: 'Watchdog' },
  ];

  const generatePDF = (id: string, title: string) => {
    setGenerating(id);
    
    setTimeout(() => {
      const doc = new jsPDF();
      
      doc.setFontSize(22);
      doc.text("IN THE COURT OF THE DISTRICT MAGISTRATE", 20, 30);
      
      doc.setFontSize(14);
      doc.text(`PETITION: ${title.toUpperCase()}`, 20, 50);
      
      doc.setFontSize(10);
      doc.text(`Case ID: ${mockCaseData.caseId}`, 160, 50);
      
      doc.line(20, 55, 190, 55);
      
      doc.setFontSize(12);
      doc.text("TO THE HONORABLE JUDGE,", 20, 70);
      doc.text("The petitioner seeks the following order based on the principles of natural justice...", 20, 80);
      
      if (extractedDetails?.summary) {
        doc.setFontSize(10);
        doc.text("ALLEGATION SUMMARY:", 20, 95);
        const splitSummary = doc.splitTextToSize(extractedDetails.summary, 170);
        doc.text(splitSummary, 20, 105);
        
        let yPos = 105 + (splitSummary.length * 5) + 10;
        doc.text("GROUNDS FOR BAIL:", 20, yPos);
        doc.text("1. Ground A: Absence of criminal record.", 20, yPos + 10);
        doc.text("2. Ground B: Cooperation with investigating agencies.", 20, yPos + 20);
        doc.text("3. Ground C: Violation of D.K. Basu guidelines during arrest.", 20, yPos + 30);
      } else {
        doc.text("1. Ground A: Absence of criminal record.", 20, 100);
        doc.text("2. Ground B: Cooperation with investigating agencies.", 20, 110);
        doc.text("3. Ground C: Violation of D.K. Basu guidelines during arrest.", 20, 120);
      }
      
      doc.setFontSize(8);
      doc.setTextColor(150);
      doc.text("GENERATED BY BAILBRIDGE AI / NAMMA NYAYA AGENT", 20, 280);
      doc.text("THIS IS A DRAFT. CONSULT AN ADVOCATE BEFORE SUBMISSION.", 20, 285);
      
      doc.save(`BailBridge_${id}.pdf`);
      setGenerating(null);
    }, 1500);
  };

  return (
    <div className="max-w-6xl mx-auto px-4 py-8">
      <div className="flex items-center gap-8 mb-16 flex-col md:flex-row text-center md:text-left border-b border-white/5 pb-12">
        <div className="w-16 h-16 rounded-xl bg-blue-600/10 flex items-center justify-center text-blue-400 border border-blue-500/20 shrink-0">
          <Files className="w-8 h-8" />
        </div>
        <div>
          <div className="text-[10px] font-black uppercase tracking-[0.3em] text-blue-400 mb-2">Automated Drafting</div>
          <h1 className="text-4xl font-semibold mb-3 text-white uppercase tracking-tight">Document Architect</h1>
          <p className="text-slate-500 max-w-2xl leading-relaxed text-sm italic">
            Generate court-ready petitions with high precision. Optimized for BNSS 2023 jurisdictional requirements.
          </p>
        </div>
      </div>

      <div className="grid grid-cols-1 lg:grid-cols-4 gap-12">
        {/* Left: Templates */}
        <div className="lg:col-span-3 grid grid-cols-1 md:grid-cols-2 gap-6">
          {templates.map((tpl) => (
            <motion.div 
              key={tpl.id}
              whileHover={{ y: -4 }}
              className="group"
            >
              <SpotlightCard className="p-8 h-full flex flex-col bg-slate-950/40 border-white/5 hover:border-blue-500/30 transition-all">
                <div className="flex justify-between items-start mb-6">
                  <span className="text-[10px] font-black uppercase tracking-widest text-slate-600 border border-white/10 px-2 py-0.5 rounded">
                    {tpl.type}
                  </span>
                  <div className="w-2 h-2 rounded-full bg-blue-500/20 group-hover:bg-blue-500 transition-colors" />
                </div>
                <h3 className="text-xl font-bold mb-3 text-white tracking-tight uppercase">{tpl.title}</h3>
                <p className="text-[13px] text-slate-500 leading-relaxed mb-8 flex-1">{tpl.description}</p>
                <div className="flex gap-3 pt-6 border-t border-white/5">
                  <Button 
                    className="flex-1 bg-blue-600 hover:bg-blue-700 text-white font-bold h-11 rounded-lg text-xs uppercase tracking-widest transition-all shadow-lg shadow-blue-600/10"
                    onClick={() => generatePDF(tpl.id, tpl.title)}
                    disabled={generating !== null}
                  >
                    {generating === tpl.id ? 'Processing...' : 'Draft Petition'}
                    <ChevronRight className="ml-2 w-4 h-4" />
                  </Button>
                  <Button 
                    size="icon" 
                    variant="outline" 
                    className="border-white/10 hover:bg-white/5 w-11 h-11"
                    onClick={() => alert("Translation to Kannada/Hindi engine initializing...")}
                  >
                    <Languages className="w-4 h-4 text-slate-500" />
                  </Button>
                </div>
              </SpotlightCard>
            </motion.div>
          ))}
        </div>

        {/* Right: Checklist / Status */}
        <div className="space-y-8">
          <SpotlightCard className="p-6 bg-slate-900/40 relative overflow-hidden">
            <div className="absolute top-0 right-0 p-4 opacity-5 group-hover:opacity-20 transition-opacity">
               <QrCode className="w-12 h-12 text-blue-500" />
            </div>
            <h3 className="text-[10px] font-black tracking-[0.2em] text-blue-400 uppercase mb-6 flex items-center gap-2">
              <QrCode className="w-4 h-4" />
              Digital Bridge QR
            </h3>
            <div className="flex flex-col items-center gap-6">
              <div className="p-3 bg-white rounded-xl shadow-2xl shadow-blue-500/20">
                <QRCodeSVG 
                  value={JSON.stringify(mockCaseData)} 
                  size={140}
                  level="H"
                  includeMargin={false}
                />
              </div>
              <p className="text-[10px] text-slate-500 text-center leading-relaxed italic">
                Scan at any **e-Seva Kendra** or **DLSA Office** to instantly import your case data for filing.
              </p>
              <Button 
                variant="outline" 
                size="sm" 
                className="w-full text-[9px] font-black uppercase tracking-widest border-white/5 hover:bg-white/5 h-10"
                onClick={() => setShowQR(!showQR)}
              >
                Refresh Session
              </Button>
            </div>
          </SpotlightCard>

          <SpotlightCard className="p-6 bg-slate-900/40">
            <h3 className="text-[10px] font-black tracking-[0.2em] text-slate-500 uppercase mb-6 flex items-center gap-2">
              <ShieldCheck className="w-4 h-4 text-blue-400" />
              Submission Protocol
            </h3>
            <div className="space-y-4">
              <CheckItem text="FIR Number verified" checked={!!extractedDetails?.fir_number} />
              <CheckItem text="Police Station details" checked={!!extractedDetails?.police_station} />
              <CheckItem text="Surety details provided" />
              <CheckItem text="Tax Identification (PAN)" />
            </div>
          </SpotlightCard>

          <div>
            <h4 className="text-[10px] font-black text-slate-600 uppercase tracking-widest mb-4 px-1">Case Archive</h4>
            <div className="space-y-2">
              {[1, 2].map((i) => (
                <div key={i} className="flex items-center justify-between group cursor-pointer hover:bg-white/5 p-3 rounded-lg border border-transparent hover:border-white/5 transition-all">
                  <div className="flex items-center gap-3">
                    <FileText className="w-4 h-4 text-slate-600 group-hover:text-blue-400" />
                    <span className="text-[11px] text-slate-500 font-medium">Bail_App_May08.pdf</span>
                  </div>
                  <Download className="w-3.5 h-3.5 text-slate-700 group-hover:text-white" />
                </div>
              ))}
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}

function CheckItem({ text, checked = false }: { text: string, checked?: boolean }) {
  return (
    <div className="flex items-center gap-3 text-xs">
      <div className={`w-4 h-4 rounded-full border ${checked ? 'bg-emerald-500 border-emerald-500' : 'border-white/20'} flex items-center justify-center shrink-0`}>
        {checked && <CheckCircle2 className="w-3 h-3 text-white" />}
      </div>
      <span className={checked ? 'text-slate-300' : 'text-slate-500'}>{text}</span>
    </div>
  );
}
